// Generated by CoffeeScript 1.3.3
(function() {
  var SimpleHtml5Editor;

  SimpleHtml5Editor = (function() {

    function SimpleHtml5Editor(element, movement) {
      var btn, _i, _len, _ref;
      this.element = element;
      this.langs = ['Enter URL', 'Enter Image URL'];
      this.button_creator = [
        {
          'editor_formatting': [
            {
              'tag': 'bold',
              'format': '',
              'name': '<i class="icon-bold"></i>'
            }, {
              'tag': 'underline',
              'format': '',
              'name': '<i class="icon-underline"></i>'
            }, {
              'tag': 'strikeThrough',
              'format': '',
              'name': '<i class="icon-strikethrough"></i>'
            }, {
              'tag': 'subscript',
              'format': '',
              'name': 'T<sub>x</sub>'
            }, {
              'tag': 'superscript',
              'format': '',
              'name': 'T<sup>x</sub>'
            }
          ]
        }, {
          'editor_indentation': [
            {
              'tag': 'indent',
              'format': '',
              'name': '<b class=icon-indent-left></b>'
            }, {
              'tag': 'outdent',
              'format': '',
              'name': '<b class=icon-indent-right></b>'
            }
          ]
        }, {
          'editor_justify': [
            {
              'tag': 'justifyLeft',
              'format': '',
              'name': '<i class="icon-align-left"></i>'
            }, {
              'tag': 'justifyCenter',
              'format': '',
              'name': '<i class="icon-align-center"></i>'
            }, {
              'tag': 'justifyRight',
              'format': '',
              'name': '<i class="icon-align-right"></i>'
            }
          ]
        }, {
          'select': [
            {
              'tag': 'formatBlock',
              'format': 'p',
              'name': '<i class="icon-paragraph"></i>Paragraph'
            }, {
              'tag': 'formatBlock',
              'format': 'h1',
              'name': 'Header'
            }, {
              'tag': 'formatBlock',
              'format': 'h2',
              'name': 'Header 2'
            }, {
              'tag': 'formatBlock',
              'format': 'h3',
              'name': 'Header 3'
            }
          ]
        }
      ];
      _ref = this.button_creator;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        btn = _ref[_i];
        this.create_button(btn);
      }
      ($('.editor_button')).on('click', this.execcmd);
      ($('.editor_nav')).on('change', this.execcmd);
    }

    SimpleHtml5Editor.prototype.create_group = function(name, element) {
      var elem, html;
      html = "<div class='editor_group " + name + "'>";
      for (elem in element) {
        html += '<a href=# class=editor_button data-format=\"' + element[elem]['format'] + '\" data-tag=\"' + element[elem]['tag'] + '\"  >' + element[elem]['name'] + '</a>';
      }
      html += "</div>";
      return html;
    };

    SimpleHtml5Editor.prototype.create_select = function(element) {
      var elem, html;
      html = "<select class='editor_nav'>";
      for (elem in element) {
        html += '<option data-format=\"' + element[elem]['format'] + '\" data-tag=\"' + element[elem]['tag'] + '\"  >' + element[elem]['name'] + '</option>';
      }
      html += "</select>";
      return html;
    };

    SimpleHtml5Editor.prototype.create_button = function(btn) {
      var element, html, name;
      if (btn['tag']) {
        html = '<a class="editor_button" href="#" data-format=\"' + btn['format'] + '\" data-tag=\"' + btn['tag'] + '\"  >' + btn['name'] + '</a>';
      } else {
        for (name in btn) {
          element = btn[name];
          console.log(name, element);
        }
        if (name === "select") {
          for (name in btn) {
            element = btn[name];
            html = this.create_select(element);
          }
        }
        if (name !== "select") {
          for (name in btn) {
            element = btn[name];
            html = this.create_group(name, element);
          }
        }
      }
      return this.element.prepend(html);
    };

    SimpleHtml5Editor.prototype.execcmd = function(ev) {
      var data, tag, target;
      target = ev.target;
      if (($(target)).is('select')) {
        target = target[target.selectedIndex];
      } else if (!($(target)).is('a')) {
        target = ($(target)).parent()[0];
      } else if (!($(target)).is('a')) {
        target = ($(target)).parent()[0];
      }
      tag = target.dataset['tag'];
      console.log(target);
      if (tag === "formatBlock") {
        data = target.dataset['format'];
      } else if (tag === 'createlink' || tag === 'insertImage') {
        data = prompt(this.langs[tag]);
      }
      if (data) {
        return document.execCommand(tag, false, data);
      }
      return document.execCommand(tag, false);
    };

    return SimpleHtml5Editor;

  })();

  (function($) {
    return $.fn.simpleHtml5Editor = function() {
      var simpleHtml5Editor;
      return simpleHtml5Editor = new SimpleHtml5Editor(this);
    };
  })($);

}).call(this);
